### ISSUE TITLE
[BUG] Dark theme not applied to toasts

### ISSUE THREAD

**Issue by AnotiaWang** [getezy/ezy#36]
**Describe the bug**
Dark theme not applied to toasts

**To Reproduce**
1. Trigger a toast

**Screenshots**
![image](https://user-images.githubusercontent.com/62269186/206967509-e557bf64-9452-4228-b1e9-6ee67e051ab3.png)

**Environment:**
 - OS: Windows 11
 - Version: 22H2
 - Ezy: 1.0.0-beta.13.2

**Additional information**
The "Bug" issue template doesn't require ezy's version, which I think should be added to help debugging.

**Comment by notmedia** [comment]
@AnotiaWang Hey! Are you getting this error every startup for a short time? There was a problem with styles loading at startup when notifications showed before styles were applied which I fixed and will publish in next release.

If styles don't apply for a long time I think this is different.

> The "Bug" issue template doesn't require ezy's version, which I think should be added to help debugging.
Yeah, thank you!

**Comment by AnotiaWang** [comment]
> Are you getting this error every startup for a short time? There was a problem with styles loading at startup when notifications showed before styles were applied which I fixed and will publish in next release.

Ah yes, the bug stopped appearing after a while.

**Comment by notmedia** [comment]
Okay, I will publish release today! Thank you!

**Comment by notmedia** [comment]
@AnotiaWang [v1.0.0-beta.14](https://github.com/getezy/ezy/releases/tag/v1.0.0-beta.14) released  🚀
