### ISSUE TITLE
Provide automatic message generation template

### ISSUE THREAD

**Issue by cexll** [getezy/ezy#47]
It will be very troublesome if the message template cannot be automatically generated after importing proto

Similar to postman, add a Generate Message Example below

Open the file to generate the message template by default

<img width="682" alt="截屏2023-02-24 22 50 47" src="https://user-images.githubusercontent.com/26520956/221208722-08631783-9814-4add-806a-cf12a4bde64e.png">
<img width="547" alt="截屏2023-02-24 22 51 01" src="https://user-images.githubusercontent.com/26520956/221208773-4e1daff1-76fc-47be-9c23-bca87e471b9f.png">

Thank you for letting us use the very useful GrpcGUI

**Comment by notmedia** [comment]
Hey @cexll! Thank you for your feedback 🙏. Yeah, this feature is coming, I will do my best to add this as soon as possible. Right now I'm doing the big work - rewriting the storage and the tab containers. After this I will add auto-mocking feature fast.

There is already created issue #3  lets track it there. I will close this issue as a duplicate.
